from typing import Literal

Language = Literal["english", "german"]

translations = {
    "english": {
        "title": "Fantasy Tribe Game",
        "game_tab": "Game",
        "race_theme_label": "Choose theme to influence race generation",
        "race_themes": ["", "Men", "High Elves ", "Wood Elves", "Dark Elves", "Dwarves", "Halflings", "Orcs",
                             "Goblins", "Gnomes", "Trolls", "Ogres", "Kobolds", "Skaven", "Vampires", "Lycanthropes",
                             "Giants", "Valkyries", "Norns", "Nephilim", "Fairies", "Sprites", "Pixies", "Changelings",
                             "Angels", "Demons", "Celestials", "Fauns", "Ghuls", "Ifrits", "Unicorns", "Griffin",
                             "Wyverns", "Centaurs", "Minotaurs", "Merfolk", "Naga", "Djinn", "Aasimar", "Tieflings",
                             "Dragonborn", "Kitsune", "Tengu", "Sylphs", "Dryads", "Nymphs", "Harpies", "Satyrs",
                             "Phoenix", "Basilisks", "Chimeras", "Gryphons", "Liches", "Elementals", "Golems",
                             "Gargoyles", "Wendigo", "Yokai", "Rakshasa", "Selkies", "Banshees", "Revenants",
                             "Succubi/Incubi", "Doppelgangers", "Wraiths", "Fomorians", "Firbolg", "Lizardfolk",
                             "Kenku", "Aarakocra", "Tabaxi", "Yuan-ti", "Genasi", "Warforged", "Automata"],
        "settings_tab": "Settings",
        "start_button": "Generate Tribe Choices",
        "tribe_choices_label": "Available Tribes",
        "tribe_selection_label": "Select your tribe",
        "select_tribe_button": "Select Tribe",
        "tribe_overview_label": "Tribe Overview",
        "relationships_label": "Relationships",
        "recent_history_label": "Recent History",
        "current_situation_label": "Current Situation",
        "save_button": "Save Game",
        "load_button": "Load Game",
        "message_display_label": "System Messages",
        "language_config": "Language Configuration",
        "story_llm_config": "Story LLM Configuration",
        "summary_llm_config": "Summary LLM Configuration",
        "settings_save_btn": "Save Settings",
        "settings_status_label": "Settings Status",
    },
     "german": {
        "title": "Fantasy-Stammesspiel",
        "game_tab": "Spiel",
        "race_theme_label": "Wähle ein Thema, um die Rassengenerierung zu beeinflussen",
        "race_themes": ["", "Menschen", "Hochelfen", "Waldelfen", "Dunkelelfen", "Zwerge", "Halblinge", "Orks",
                    "Goblins", "Gnome", "Trolle", "Oger", "Kobolde", "Skaven", "Vampire", "Werwesen",
                    "Riesen", "Walküren", "Nornen", "Nephilim", "Feen", "Naturgeister", "Pixies", "Wechselbälger",
                    "Engel", "Dämonen", "Himmlische Wesen", "Faune", "Ghule", "Ifrits", "Einhörner", "Greife",
                    "Wyvern", "Zentauren", "Minotauren", "Meervolk", "Nagas", "Dschinns", "Aasimar", "Tieflinge",
                    "Drachengeborene", "Kitsune", "Tengu", "Sylphen", "Dryaden", "Nymphen", "Harpyien", "Satyrn",
                    "Phönix", "Basilisken", "Chimären", "Greifen", "Lichs", "Elementare", "Golems",
                    "Gargoyles", "Wendigos", "Yokai", "Rakshasas", "Selkies", "Banshees", "Wiedergänger",
                    "Sukkubi/Inkubi", "Doppelgänger", "Geister", "Fomori", "Firbolg", "Echsenmenschen",
                    "Kenku", "Aarakocra", "Tabaxi", "Yuan-ti", "Genasi", "Kriegsgeschmiedete", "Automaten"],
        "settings_tab": "Einstellungen",
        "start_button": "Stammesauswahl generieren",
        "tribe_choices_label": "Verfügbare Stämme",
        "tribe_selection_label": "Wähle deinen Stamm",
        "select_tribe_button": "Stamm auswählen",
        "tribe_overview_label": "Stammesübersicht",
        "relationships_label": "Beziehungen",
        "recent_history_label": "Jüngste Geschichte",
        "current_situation_label": "Aktuelle Situation",
        "save_button": "Spiel speichern",
        "load_button": "Spiel laden",
        "message_display_label": "Systemnachrichten",
        "language_config": "Sprachkonfiguration",
        "story_llm_config": "Story-LLM-Konfiguration",
        "summary_llm_config": "Zusammenfassungs-LLM-Konfiguration",
        "settings_save_btn": "Einstellungen speichern",
        "settings_status_label": "Status der Einstellungen"
    }
}